In [33]:
##Exemplo 4  -  Multilicação de matrizes.
import tensorflow as tf

In [34]:
# Construindo matrizes
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[0,0],[1,0],[0,1]])


In [35]:
resultado = tf.matmul(A,B)

In [36]:
print(tf.Session().run(resultado))

[[2 3]
 [5 6]]


In [37]:
x = tf.constant([0,1,0])

In [38]:
print(tf.Session().run(x))

[0 1 0]


In [39]:
print(x.shape)

(3,)


In [40]:
#Expansão da matriz
x = tf.expand_dims(x,1)

In [41]:
print(x.shape)

(3, 1)


In [43]:
resultado2 = tf.matmul(A,x)

In [45]:
#Mostrando o resultado da multiplicação
print(tf.Session().run(resultado2))

[[2]
 [5]]


In [47]:
#Usando a função para matriz transposta.
transposta = tf.transpose(A)

In [50]:
print(tf.Session().run(A))

[[1 2 3]
 [4 5 6]]


In [51]:
print(tf.Session().run(transposta))


[[1 4]
 [2 5]
 [3 6]]
